### PR TITLE
asset_id as full_path if contains "projects"

### PR DESCRIPTION
**Pull request by brookisme**
Minimal change to allow users to delete asset_ids that are in projects.  Similar control should probably be added to uploads as well.

### CODE REVIEW

**Comment by tracek** [comment]
Nice approach, but my worry here is that user might have a directory 'projects', e.g. users/user/projects - how would we know which to delete? Adding a switch is not nicest option, but explicit. Another option would be to remove relative paths completely. Simplifies the code, no ambiguity. It kills though backward compatibility and calls for a bit more typing .

**Comment by tracek** [comment]
After some thinking I decided to remove altogether the option for using 'relative' path. The code and command line interface is now more clear. What do you think?

**Comment by brookisme** [comment]
Certainly - only allowing a full-path would be unambiguous.  

That said, If you do want to keep the relative path an easy solution would be to use regex  with`/^users\//`  and `/^projects\//` - using the carrot (^) to ensure that `projects`  or `users` comes at the beginning and the escaped forward slash (\\/) to ensure they are followed by a trailing forward slash (though you could probably drop this part).

**Comment by tracek** [comment]
Thanks, the regex would work just great, short of one situation:
`projects/stuff/mycollection`
Now, is it relative or absolute? Naturally 99% of users would mean here fully qualified path, but in theory there could be this one person that meant:
users/user/projects/stuff/mycollection

Similar thing with:
`projects/mycollection`

It's not a valid absolute path, but perfectly fine relative.

These are edge cases that are unlikely to happen, I agree. I am actually more concerned that in future there might be more name spaces added next to `users` and `projects`. 

However, if there's a strong demand to have the short, relative path, then indeed your regex would be the best solution here.

**Comment by brookisme** [comment]
I don't think there's a strong demand and absolute path idea is probably
best.  As long as were hashing out ideas though - you could protect against
`projects/mycollection` with regex as well - and for future name spaces you
could just put all-absolute-path-regex's in a config variable so that you
can easily add new paths.  I personally wouldn't worry about `
projects/stuff/mycollection` as a relative path.

But again I think your first instinct was right - sometimes simplest is
best :)

**Pull request closed without merging**
